Lesson 10
alexshent/alevelhw pull request #1
Opened 2022-07-08 04:06 UTC by alexshent

2022-07-09 22:42 UTC, Fabolo12 requested changes

2022-07-09 22:42 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/model/Automobile.java
> +    public boolean equals(Object object) {
нужно еще переопределить hashCode

2022-07-09 22:42 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/model/Manufacturer.java
> +public interface Manufacturer {
Этот интерфейс лишний

2022-07-09 22:42 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/model/Vehicle.java
> +    protected Manufacturer manufacturer;
Поле производителя, в твоей реализации, должно быть в конкретных классах

2022-07-09 22:42 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/repository/Repository.java
> +public interface Repository<T> {
Правильное решение

2022-07-09 22:42 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/service/Service.java
> +    public Repository<V> getRepository() {
Этот метод лишний, надо все делать через сервисы

2022-07-11 14:12 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/model/Automobile.java
> +    public boolean equals(Object object) {
hashCode() overridden

2022-07-11 14:26 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/model/Manufacturer.java
> +public interface Manufacturer {
deleted Manufacturer interface

2022-07-11 14:26 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/model/Vehicle.java
> +    protected Manufacturer manufacturer;
manufacturer field moved to specific classes

2022-07-11 14:45 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/service/Service.java
> +    public Repository<V> getRepository() {
deleted method getRepository()

2022-07-11 22:00 UTC, Fabolo12 approved these changes

2022-07-12 00:07 UTC, merged