Lesson 11
alexshent/alevelhw pull request #2
Opened 2022-07-13 18:15 UTC by alexshent

2022-07-15 23:57 UTC, Fabolo12 requested changes

2022-07-15 23:57 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/service/AutomobileService.java
>          repository = new AutomobileRepository();
Думаю этот конструктор лишний

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/model/AutomobileTest.java
> +class AutomobileTest {
На модели тесты не нужны, в них них нет логики которую ты пишешь сам

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        repository.create(autos);
Этот вызов ничего не даст, т.к. у тебя мок

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        Mockito.when(repository.create(service.createAutos(numberOfAutos))).thenReturn(true);
Сюда надо передавать аргумент, а не результат выполнения другого метода

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        // then
По факту у тебя нет вызова тестируемого метода

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        Mockito.verifyNoMoreInteractions(repository);
Это должен быть отдельный тестовый метод, с учетом поправок выше

2022-07-15 23:57 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/service/AutomobileServiceTest.java
> +        assertEquals(expectedListSize, actualListSize);
А как тут мы проверяем работу метода saveProducts ?

2022-07-16 07:42 UTC, alexshent commented on src/test/java/ua/com/alevel/alexshent/model/AutomobileTest.java
> +class AutomobileTest {
ok

2022-07-17 19:25 UTC, Fabolo12 approved these changes

2022-07-17 19:25 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        AutomobileRepository repository = new AutomobileRepository();
Создание лучше делать в сетапе

2022-07-17 19:25 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        Automobile automobileMock = mock(Automobile.class);
Модели не мокируем

2022-07-17 19:25 UTC, Fabolo12 commented on src/test/java/ua/com/alevel/alexshent/service/AutomobileServiceTest.java
> +class AutomobileServiceTest {
А тут, при текущем подходе, твой тест зависит от репозитория, поскольку он не мокирован

2022-07-17 22:39 UTC, alexshent commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        AutomobileRepository repository = new AutomobileRepository();
ok

2022-07-17 22:43 UTC, alexshent commented on src/test/java/ua/com/alevel/alexshent/repository/AutomobileRepositoryTest.java
> +        Automobile automobileMock = mock(Automobile.class);
ok

2022-07-17 23:08 UTC, alexshent commented on src/test/java/ua/com/alevel/alexshent/service/AutomobileServiceTest.java
> +class AutomobileServiceTest {
ok

2022-07-26 06:20 UTC, merged