Lesson 15
alexshent/alevelhw pull request #7
Opened 2022-07-31 04:37 UTC by alexshent

2022-07-31 22:10 UTC, Fabolo12 requested changes

2022-07-31 22:10 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/Demo.java
> +        CommandExecutor commandExecutor = new CommandExecutor(new AutomobileService());
а почему тут хардкор именно на авто

2022-07-31 22:10 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/binarytree/Node.java
> +    private Comparator<T> comparator;
тут это лишнее

2022-07-31 22:10 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/binarytree/Node.java
> +    }
и это

2022-07-31 22:10 UTC, Fabolo12 commented on src/main/java/ua/com/alevel/alexshent/command/CommandExecutor.java
> +    }
такой подход убивает всю гибкость

2022-08-01 04:42 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/binarytree/Node.java
> +    private Comparator<T> comparator;
removed

2022-08-01 04:42 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/binarytree/Node.java
> +    }
removed

2022-08-01 05:54 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/Demo.java
> +        CommandExecutor commandExecutor = new CommandExecutor(new AutomobileService());
changed

2022-08-01 05:54 UTC, alexshent commented on src/main/java/ua/com/alevel/alexshent/command/CommandExecutor.java
> +    }
updated

2022-08-05 20:44 UTC, Fabolo12 approved these changes

2022-08-06 16:50 UTC, merged